	TITLE	=== Tecт тpaнcл€тopa TrnlZ80 <Ѕѕ‘> Media Corp. ===
.IDENT	/7.3.1999 21:30/	;ѕceвдooпepaтop ƒaты и Bpeмeни coздaни€ фaйлa!
LENC	EQU	13	;Ћюбoe paзумнoe знaчeниe длины зaпиcи
	AUTOORG	LENC ;Koнcтpукци€ дл€ зaдaни€ фaйлa c пocтo€ннoй длинoй зaпиceй
	ORG	1	;Ётo ORG дл€ вcex пpoчиx иcпoльзoвaний
	ORG_MIN	0
	ORG_MAX	2048
	.2716	;ѕceвдoкoмaндa дл€ зaдaни€ oбъЄмa выxoднoгo фaйлa, кpaтнoгo
;oбъЄму иcпoльзуeмoй микpocxeмы ROM. ƒpугиe aльтepнaтивы: .2732, .2764, ...
PORT	EQU	$D1+10B	;ѕpи пpиpaвнивaнии cимвoльную пepeмeнную нe нaдo мeтить
			;двoeтoчиeм, в ocтaльнoм пpиpaвнивeниe oбpaбaтывaeтc€
			;кaк мeткa
	IDENT	;Oпepaтop вcтaвки дaты вepcии тpaнcл€ции в фopмaтe ƒƒ-MMM-√√
	AUTOORG	LENC	;Aвтoпpoдвижeниe ORG (=> ORG LENC*1)
	DB	$,$+1B,$+2,$+3	;”кaзaтeль нa тeкущиe aдpeca
		1,2,T3		;„иcлoвыe кoнcтaнты мoгут быть и бeз DB и без DEFB
	DEFB	4d,O5,110B,7h,%11100111
	DEFW	Ѕѕ‘47	;Oпepaтop oбoзнaчeни€ длиннoгo aдpeca
	DEFW	Ѕѕ‘0.div.LENC	;ќператор может быть и вычил€емым (деление)
	DEF8	Ѕѕ‘46	;Oпepaтop oбoзнaчeни€ кopoткoгo aдpeca
	AUTOORG	LENC	;Aвтoпpoдвижeниe ORG (=> ORG LENC*2)
	FLT3	1.23456	;Beщecтвeннoe тpЄxcлoвнoe знaчeниe в фopмaтe IBM
	FLT2	1.23456 ;Beщecтвeннoe двуxcлoвнoe знaчeниe в фopмaтe PDP-11
	LINT	65538	;ƒec€тичнoe чeтыpЄxбaйтoвoe цeлoe
	REL	Ѕѕ‘1	;Oпepaтop oбoзнaчeни€ oтнocитeльнoгo aдpeca (8 бит)
	DBZ	'<Ѕѕ‘> Media Corporation; Ѕaxapeв M.H.; ѕepмь-1999 г.'
	DB	"—троки и",13,0Ah,"с числовыми значени€ми (бaйтами)",13,10,"вперемежку"
	STR	'“олько строка'
	STRCR	'—трока с добавлением кода <CR>'
	STRWCR	'Ётo тоже'
	STRW	'» этo строка (без добавлени€ <CR>Е'
	DBE	'+128'
			;ѕocлeдний кoд cтpoки в DBE измeн€eтc€ нa 128
	.DS	4	;Koмaндa, aнaлoгичнa€ ORG $+4, нo впиcывaeт в oблacть
			;бaйтoвыe знaчeни€ 0 в тo вpeм€ кaк ORG ocтaвл€eт
			;пpoпуcкaeмую oблacть нeизмeннoй!
	DEFW	0-24	;ѕpимep дec€тичнoй кoнcтaнты co знaкoм минуc
;	Oтcюдa cлeдуют oпepaтopы мaшинныx кoмaнд в пop€дкe вoзpacтaни€ кoдoв
;	мaшинныx кoмaнд.
Ѕѕ‘0:	NOP	;Meтки мoгут быть и c буквaми pуccкoгo aлфaвитa
	LD	BC,Ѕѕ‘52
	LD	(BC),A
	INC	BC
	INC	B
	DEC	B
	LD	B,Ѕѕ‘0
	RLCA
	EX	AF,AF"
	EX	AF,AF'
	ADD	HL,BC
	LD	A,(BC)
	DEC	BC
	INC	C
	DEC	C
	LD	C,$E
	RRCA
Ѕѕ‘1:	DJNZ	Ѕѕ‘2
	LD	DE,Ѕѕ‘51
	LD	(DE),A
	INC	DE
	INC	D
	DEC	D
	LD	D,$16	;Hex-чиcлo c пpeфикcoм $
	RLA
	JR	Ѕѕ‘1
	ADD	HL,DE
	LD	A,(DE)
	DEC	DE
	INC	E
	DEC	E
	LD	E,1EH	;Hex-чиcлo c пocтфикcoм H
	RRA
Ѕѕ‘2:	JR	NZ,Ѕѕ‘3
	LD	HL,Ѕѕ‘50
	LD	(O21042),HL	;Oct-чиcлo c пpeфикcoм O
	INC	HL
	INC	H
	DEC	H
	LD	H,46O	;Oct-чиcлo c пocтфикcoм O
	DAA
	JR	Z,Ѕѕ‘4
	ADD	HL,HL
	LD	HL,(0T02220222)	;„eтвepичнoe чиcлo c пpeфикcoм 0T
	DEC	HL
	INC	L
	DEC	L
	LD	L,056Q	;Oct-чиcлo c пocтфикcoм Q
	CPL
Ѕѕ‘3:	JR	NC,Ѕѕ‘5
	LD	SP,Ѕѕ‘49
	LD	(0011001000110010B),A	;Binary-чиcлo c пocтфикcoм B
	INC	SP
	INC	(HL)
	DEC	(HL)
	LD	(HL),54	;ƒec€тичнoe чиcлo
	SCF
	JR	C,Ѕѕ‘6
	ADD	HL,SP
	LD	A,(Ѕѕ‘14)
	DEC	SP
	INC	A
	DEC	A
	LD	A,Ѕѕ‘1
	CCF
Ѕѕ‘4:	LD	B,B
	LD	B,C
	LD	B,D
	LD	B,E
	LD	B,H
	LD	B,L
	LD	B,(HL)
	LD	B,A
	LD	C,B
	LD	C,C
	LD	C,D
	LD	C,E
	LD	C,H
	LD	C,L
	LD	C,(HL)
	LD	C,A
Ѕѕ‘5:	LD	D,B
	LD	D,C
	LD	D,D
	LD	D,E
	LD	D,H
	LD	D,L
	LD	D,(HL)
	LD	D,A
	LD	E,B
	LD	E,C
	LD	E,D
	LD	E,E
	LD	E,H
	LD	E,L
	LD	E,(HL)
	LD	E,A
Ѕѕ‘6:	LD	H,B
	LD	H,C
	LD	H,D
	LD	H,E
	LD	H,H
	LD	H,L
	LD	H,(HL)
	LD	H,A
	LD	L,B
	LD	L,C
	LD	L,D
	LD	L,E
	LD	L,H
	LD	L,L
	LD	L,(HL)
	LD	L,A
Ѕѕ‘7:	LD	(HL),B
	LD	(HL),C
	LD	(HL),D
	LD	(HL),E
	LD	(HL),H
	LD	(HL),L
	HALT
	LD	(HL),A
	LD	A,B
	LD	A,C
	LD	A,D
	LD	A,E
	LD	A,H
	LD	A,L
	LD	A,(HL)
	LD	A,A
Ѕѕ‘8:	ADD	A,B
	ADD	A,C
	ADD	A,D
	ADD	A,E
	ADD	A,H
	ADD	A,L
	ADD	A,(HL)
	ADD	A,A
	ADC	A,B
	ADC	A,C
	ADC	A,D
	ADC	A,E
	ADC	A,H
	ADC	A,L
	ADC	A,(HL)
	ADC	A,A
Ѕѕ‘9:	SUB	B
	SUB	C
	SUB	D
	SUB	E
	SUB	H
	SUB	L
	SUB	(HL)
	SUB	A
	SBC	A,B
	SBC	A,C
	SBC	A,D
	SBC	A,E
	SBC	A,H
	SBC	A,L
	SBC	A,(HL)
	SBC	A,A
Ѕѕ‘10:	AND	B
	AND	C
	AND	D
	AND	E
	AND	H
	AND	L
	AND	(HL)
	AND	A
	XOR	B
	XOR	C
	XOR	D
	XOR	E
	XOR	H
	XOR	L
	XOR	(HL)
	XOR	A
Ѕѕ‘11:	OR	B
	OR	C
	OR	D
	OR	E
	OR	H
	OR	L
	OR	(HL)
	OR	A
	CP	B
	CP	C
	CP	D
	CP	E
	CP	H
	CP	L
	CP	(HL)
	CP	A
Ѕѕ‘12:	RET	NZ
	POP	BC
	JP	NZ,Ѕѕ‘7
	JP	Ѕѕ‘8
	CALL	NZ,Ѕѕ‘9
	PUSH	BC
	ADD	A,%11000110 ;ещЄ один вариант написани€ двоичных чисел (дл€ совместимости с другими компил€торами)
	RST	0
	RET	Z
	RET
	JP	Z,Ѕѕ‘10
;	DB	0CBH	;SIDE 1
	CALL	Z,Ѕѕ‘11
	CALL	Ѕѕ‘12
	ADC	A,0CEH	;Ecли Hex-чиcлo c пocтфикcoм H нaчинaeтc€ c буквы,
	RST	8	;To пepeд ним нaдo cтaвить нoль!
Ѕѕ‘13:	RET	NC
	POP	DE
	JP	NC,Ѕѕ‘13
	OUT	(PORT),A
	CALL	NC,Ѕѕ‘14
	PUSH	DE
	SUB	326O	;Oct-чиcлo c пocтфикcoм O
	RST	10H
	RET	C
	EXX
	JP	C,Ѕѕ‘15
	IN	A,(PORT+8)
	CALL	C,Ѕѕ‘16
;	DB	0DDH	;SIDE 2
	SBC	A,$DE
	RST	18H
Ѕѕ‘14:	RET	P0
	POP	HL
	JP	P0,Ѕѕ‘17
	EX	(SP),HL
	CALL	P0,Ѕѕ‘21
	PUSH	HL
	AND	0B11100110	;ƒвоичное число с префиксом 0B
	RST	20H
	RET	PE
	JP	(HL)
	JP	PE,Ѕѕ‘19
	EX	DE,HL
	CALL	PE,Ѕѕ‘20
;	DB	$ED	;SIDE 3
	XOR	$EE
	RST	28H
Ѕѕ‘15:	RET	P
	POP	AF
	JR	P,Ѕѕ‘18	;Oшибкa, oт пpeжниx вepcий
	JP	P,Ѕѕ‘18
	DI
	CALL	P,Ѕѕ‘22
	PUSH	AF
	OR	11110110B
	RST	30H
	RET	M
	LD	SP,HL
	JP	M,Ѕѕ‘23
	EI
	CALL	M,Ѕѕ‘24
;	DB	0FDH	;SIDE 4
	CP	376Q
	RST	38H
Ѕѕ‘16:	RLC	B	;ѕepвoe pacшиpeниe кoмaнд: ѕpeфикc $CB
	RLC	C
	RLC	D
	RLC	E
	RLC	H
	RLC	L
	RLC	(HL)
	RLC	A
	RRC	B
	RRC	C
	RRC	D
	RRC	E
	RRC	H
	RRC	L
	RRC	(HL)
	RRC	A
Ѕѕ‘17:	RL	B
	RL	C
	RL	D
	RL	E
	RL	H
	RL	L
	RL	(HL)
	RL	A
	RR	B
	RR	C
	RR	D
	RR	E
	RR	H
	RR	L
	RR	(HL)
	RR	A
Ѕѕ‘18:	SLA	B
	SLA	C
	SLA	D
	SLA	E
	SLA	H
	SLA	L
	SLA	(HL)
	SLA	A
	SRA	B
	SRA	C
	SRA	D
	SRA	E
	SRA	H
	SRA	L
	SRA	(HL)
	SRA	A
Ѕѕ‘19:	SRL	B
	SRL	C
	SRL	D
	SRL	E
	SRL	H
	SRL	L
	SRL	(HL)
	SRL	A
Ѕѕ‘20:	BIT	0,B
	BIT	0,C
	BIT	0,D
	BIT	0,E
	BIT	0,H
	BIT	0,L
	BIT	0,(HL)
Ѕит0	EQU	0
	BIT	Ѕит0,A ;ƒл€ безоперандных команд операнд в виде цифры можно и приравниваемым выражением задавать
	BIT	1,B
	BIT	1,C
	BIT	1,D
	BIT	1,E
	BIT	1,H
	BIT	1,L
	BIT	1,(HL)
	BIT	1,A
Ѕѕ‘21:	BIT	2,B
	BIT	2,C
	BIT	2,D
	BIT	2,E
	BIT	2,H
	BIT	2,L
	BIT	2,(HL)
	BIT	2,A
	BIT	3,B
	BIT	3,C
	BIT	3,D
	BIT	3,E
	BIT	3,H
	BIT	3,L
	BIT	3,(HL)
	BIT	3,A
Ѕѕ‘22:	BIT	4,B
	BIT	4,C
	BIT	4,D
	BIT	4,E
	BIT	4,H
	BIT	4,L
	BIT	4,(HL)
	BIT	4,A
	BIT	5,B
	BIT	5,C
	BIT	5,D
	BIT	5,E
	BIT	5,H
	BIT	5,L
	BIT	5,(HL)
	BIT	5,A
Ѕѕ‘23:	BIT	6,B
	BIT	6,C
	BIT	6,D
	BIT	6,E
	BIT	6,H
	BIT	6,L
	BIT	6,(HL)
	BIT	6,A
	BIT	7,B
	BIT	7,C
	BIT	7,D
	BIT	7,E
	BIT	7,H
	BIT	7,L
	BIT	7,(HL)
	BIT	7,A
Ѕѕ‘24:	RES	0,B
	RES	0,C
	RES	0,D
	RES	0,E
	RES	0,H
	RES	0,L
	RES	0,(HL)
	RES	0,A
	RES	1,B
	RES	1,C
	RES	1,D
	RES	1,E
	RES	1,H
	RES	1,L
	RES	1,(HL)
	RES	1,A
Ѕѕ‘25:	RES	2,B
	RES	2,C
	RES	2,D
	RES	2,E
	RES	2,H
	RES	2,L
	RES	2,(HL)
	RES	2,A
	RES	3,B
	RES	3,C
	RES	3,D
	RES	3,E
	RES	3,H
	RES	3,L
	RES	3,(HL)
	RES	3,A
Ѕѕ‘26:	RES	4,B
	RES	4,C
	RES	4,D
	RES	4,E
	RES	4,H
	RES	4,L
	RES	4,(HL)
	RES	4,A
	RES	5,B
	RES	5,C
	RES	5,D
	RES	5,E
	RES	5,H
	RES	5,L
	RES	5,(HL)
	RES	5,A
Ѕѕ‘27:	RES	6,B
	RES	6,C
	RES	6,D
	RES	6,E
	RES	6,H
	RES	6,L
	RES	6,(HL)
	RES	6,A
	RES	7,B
	RES	7,C
	RES	7,D
	RES	7,E
	RES	7,H
	RES	7,L
	RES	7,(HL)
	RES	7,A
Ѕѕ‘28:	SET	0,B
	SET	0,C
	SET	0,D
	SET	0,E
	SET	0,H
	SET	0,L
	SET	0,(HL)
	SET	0,A
	SET	1,B
	SET	1,C
	SET	1,D
	SET	1,E
	SET	1,H
	SET	1,L
	SET	1,(HL)
	SET	1,A
Ѕѕ‘29:	SET	2,B
	SET	2,C
	SET	2,D
	SET	2,E
	SET	2,H
	SET	2,L
	SET	2,(HL)
	SET	2,A
	SET	3,B
	SET	3,C
	SET	3,D
	SET	3,E
	SET	3,H
	SET	3,L
	SET	3,(HL)
	SET	3,A
Ѕѕ‘30:	SET	4,B
	SET	4,C
	SET	4,D
	SET	4,E
	SET	4,H
	SET	4,L
	SET	4,(HL)
	SET	4,A
	SET	5,B
	SET	5,C
	SET	5,D
	SET	5,E
	SET	5,H
	SET	5,L
	SET	5,(HL)
	SET	5,A
Ѕѕ‘31:	SET	6,B
	SET	6,C
	SET	6,D
	SET	6,E
	SET	6,H
	SET	6,L
	SET	6,(HL)
	SET	6,A
	SET	7,B
	SET	7,C
	SET	7,D
	SET	7,E
	SET	7,H
	SET	7,L
	SET	7,(HL)
	SET	7,A
Ѕѕ‘32:	ADD	IX,BC	;Bтopoe (IX) pacшиpeниe кoмaнд: ѕpeфикc $DD
	ADD	IX,DE
Ѕѕ‘33:	LD	IX,Ѕѕ‘25
	LD	(Ѕѕ‘26),IX
	INC	IX
	ADD	IX,IX
	LD	IX,(Ѕѕ‘27)
	DEC	IX
Ѕѕ‘34:	INC	(IX+$34)
	DEC	(IX+$35)
	LD	(IX+$DD),$36
	ADD	IX,SP
Ѕѕ‘35:	LD	B,(IX+46H)
	LD	C,(IX+4EH)
	LD	D,(IX+56H)
	LD	E,(IX+5EH)
	LD	H,(IX+66H)
	LD	L,(IX+6EH)
Ѕѕ‘36:	LD	(IX+$70),B
	LD	(IX+$71),C
	LD	(IX+$72),D
	LD	(IX+$73),E
	LD	(IX+$74),H
	LD	(IX+$75),L
	LD	(IX+$77),A
	LD	A,(IX+7EH)
Ѕѕ‘37:	ADD	A,(IX+$86)
	ADC	A,(IX+$8E)
	SUB	(IX+$96)
	SBC	A,(IX+$9E)
	AND	(IX+$A6)
	XOR	(IX+$AE)
	OR	(IX+$B6)
	CP	(IX+$BE)
Ѕѕ‘38:	POP	IX
	EX	(SP),IX
	PUSH	IX
	JP	(IX)
	LD	SP,IX
Ѕѕ‘39:	RLC	(IX+$06)	;ѕoдcтpaницa (IX) втopoгo pacшиpeни€ кoмaнд
	RRC	(IX+$0E)
	RL	(IX+$16)
	RR	(IX+$1E)
	SLA	(IX+$26)
	SRA	(IX+$2E)
	SRL	(IX+$3E)
	BIT	0,(IX+$46)
	BIT	1,(IX+$4E)
	BIT	2,(IX+$56)
	BIT	3,(IX+$5E)
	BIT	4,(IX+$66)
	BIT	5,(IX+$6E)
	BIT	6,(IX+$76)
	BIT	7,(IX+$7E)
	RES	0,(IX+$86)
	RES	1,(IX+$8E)
	RES	2,(IX+$96)
	RES	3,(IX+$9E)
	RES	4,(IX+$A6)
	RES	5,(IX+$AE)
	RES	6,(IX+$B6)
	RES	7,(IX+$BE)
	SET	0,(IX+$C6)
	SET	1,(IX+$CE)
	SET	2,(IX+$D6)
	SET	3,(IX+$DE)
	SET	4,(IX+$E6)
	SET	5,(IX+$EE)
	SET	6,(IX+$F6)
	SET	7,(IX+$FE)
Ѕѕ‘40:	IN	B,(C)	;Tpeтьe pacшиpeниe кoмaнд: ѕpeфикc $ED
	OUT	(C),B
	SBC	HL,BC
	LD	(Ѕѕ‘28),BC
	NEG
	RETN
	IM	0
	IM0
	LD	1,A
	IN	C,(C)
	OUT	(C),C
	ADC	HL,BC
	LD	BC,(Ѕѕ‘29)
	RET	1
	RET	I
	RETI
Ѕѕ‘41:	IN	D,(C)
	OUT	(C),D
	SBC	HL,DE
	LD	(Ѕѕ‘30),DE
	IM	1
	IM1
	LD	A,1
	IN	E,(C)
	OUT	(C),E
	ADC	HL,DE
	LD	DE,(Ѕѕ‘31)
	IM	2
	IM2
Ѕѕ‘42:	IN	H,(C)
	OUT	(C),H
	SBC	HL,HL
	RRD
	IN	L,(C)
	OUT	(C),L
	ADC	HL,HL
	RLD
Ѕѕ‘43:	SBC	HL,SP
	LD	(Ѕѕ‘32),SP
	IN	A,(C)
	OUT	(C),A
	ADC	HL,SP
	LD	SP,(Ѕѕ‘33)
Ѕѕ‘44:	LDI
	CPI
	INI
	OUTI
	LDD
	CP0
	IND
	OUTD
	LDIR
	CPIR
	INIR
	OTIR
	LDDR
	CPDR
	INDR
	OTDR
Ѕѕ‘45:	ADD	IY,BC	;„eтвЄpтoe (IY) pacшиpeниe кoмaнд: ѕpeфикc $FD
	ADD	IY,DE
Ѕѕ‘46:	LD	IY,Ѕѕ‘44
	LD	(Ѕѕ‘45),IY
	INC	IY
	ADD	IY,IY
	LD	IY,(Ѕѕ‘46)
	DEC	IY
Ѕѕ‘47:	INC	(IY+$34)
	DEC	(IY+$35)
	LD	(IY+$FD),$36
	ADD	IY,SP
Ѕѕ‘48:	LD	B,(IY+46H)
	LD	C,(IY+4EH)
	LD	D,(IY+56H)
	LD	E,(IY+5EH)
	LD	H,(IY+66H)
	LD	L,(IY+6EH)
Ѕѕ‘49:	LD	(IY+$70),B
	LD	(IY+$71),C
	LD	(IY+$72),D
	LD	(IY+$73),E
	LD	(IY+$74),H
	LD	(IY+$75),L
	LD	(IY+$77),A
	LD	A,(IY+7EH)
Ѕѕ‘50:	ADD	A,(IY+$86)
	ADC	A,(IY+$8E)
	SUB	(IY+$96)
	SBC	A,(IY+$9E)
	AND	(IY+$A6)
	XOR	(IY+$AE)
	OR	(IY+$B6)
	CP	(IY+$BE)
Ѕѕ‘51:	POP	IY
	EX	(SP),IY
	PUSH	IY
	JP	(IY)
	LD	SP,IY
Ѕѕ‘52:	RLC	(IY+6)	;ѕoдcтpaницa (IY) чeтвЄpтoгo pacшиpeни€ кoмaнд
	RRC	(IY+$E)
	RL	(IY+$16)
	RR	(IY+$1E)
	SLA	(IY+$26)
	SRA	(IY+$2E)
	SRL	(IY+$3E)
	BIT	0,(IY+$46)
	BIT	1,(IY+$4E)
	BIT	2,(IY+$56)
	BIT	3,(IY+$5E)
	BIT	4,(IY+$66)
	BIT	5,(IY+$6E)
	BIT	6,(IY+$76)
	BIT	7,(IY+$7E)
	RES	0,(IY+$86)
	RES	1,(IY+$8E)
	RES	2,(IY+$96)
	RES	3,(IY+$9E)
	RES	4,(IY+$A6)
	RES	5,(IY+$AE)
	RES	6,(IY+$B6)
	RES	7,(IY+$BE)
	SET	0,(IY+$C6)
	SET	1,(IY+$CE)
	SET	2,(IY+$D6)
	SET	3,(IY+$DE)
	SET	4,(IY+$E6)
	SET	5,(IY+$EE)
	SET	6,(IY+$F6)
	SET	7,(IY+$FE)
CONST_Demo	EQU	0x01020304
	DB	.Lo.CONST_Demo,.Hi.CONST_Demo,.Byte3.CONST_Demo,.Byte4.CONST_Demo
	END
